---

#-------------------------------------------------------------------------------

- name: Checking for server certificates in vault repository
  local_action: stat path="vault/host_certs/{{ inventory_hostname }}"
  register: server_certs_present_check

- block:
    - name: Managing server certificate directory
      file:
        path: "{{ hm_certified__cert_host_dir }}"
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Managing server certificate subdirectories
      file:
        path: "{{ hm_certified__cert_host_dir }}/{{ item.path }}"
        state: directory
        mode: '{{ item.mode }}'
      with_filetree: "vault/host_certs/{{ inventory_hostname }}/"
      when: item.state == 'directory'

    - name: Uploading server certificates
      copy:
        src: "{{ item.src }}"
        dest: "{{ hm_certified__cert_host_dir }}/{{ item.path }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_filetree: "vault/host_certs/{{ inventory_hostname }}/"
      when: item.state == 'file'

  when: server_certs_present_check.stat.isdir is defined and server_certs_present_check.stat.isdir

#-------------------------------------------------------------------------------

- name: Managing central certificate repository
  file:
    path: "{{ hm_certified__cert_ca_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Managing central certificate private key repository
  file:
    path: "{{ hm_certified__cert_key_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Managing trusted CA certificate repository
  file:
    path: "{{ hm_certified__trustedcert_ca_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Checking for CA certificates in local repository
  local_action: stat path="vault/ca_certs"
  register: ca_certs_present_check

- name: Uploading CA certificates to central certificate repository
  copy:
    src: "{{ item }}"
    dest: "{{ hm_certified__cert_ca_dir }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "vault/ca_certs/*.pem"
  when: ca_certs_present_check.stat.isdir is defined and ca_certs_present_check.stat.isdir
  notify: Rehash all CA certificates

- name: Uploading CA certificates to trusted CA certificate repository
  copy:
    src: "{{ item }}"
    dest: "{{  hm_certified__trustedcert_ca_dir }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "vault/ca_certs/*.pem"
  when: ca_certs_present_check.stat.isdir is defined and ca_certs_present_check.stat.isdir
  notify: Rehash trusted CA certificates
